#!/bin/bash

docker run --rm -it -v ./autograder/temp_sub:/autograder/submission \
                    -v ./autograder/temp_rez:/autograder/results \
                    -v ./autograder/sample_output.json:/autograder/submission_metadata.json \
                    --workdir /autograder \
                    os-gradescope-autograders:latest bash

#                    -v ./hw:/Gradescope_Setup/hw:ro \
