#!/bin/bash

# first arg is branch
# second arg is directory
# third arg is url
# Example:
# clone_dir buddy xv6-riscv https://github.com/rhit-csse332/csse332-labs.git
BRANCH=$1
DIR=$2
URL=$3
# --no-checkout avoids us from downloading unneeded junk
git clone --no-checkout $URL
cd csse332-labs
git checkout $BRANCH
#setups sparse checkout https://github.blog/2020-01-17-bring-your-monorepo-down-to-size-with-sparse-checkout/
git sparse-checkout set --cone
git sparse-checkout set $DIR #clones only xv6-riscv/ DIR
cd ..
#SVN is no longer supported (https://github.blog/2023-01-20-sunsetting-subversion-support/)
#svn export https://github.com/rhit-csse332/csse332-labs/branches/buddy/xv6-riscv/ > /dev/null
