#!/usr/bin/env bash
# Set up autograder files

#svn up /autograder/hw > /dev/null #svn is no longer supported

#================= set up environment variables =================================
export AUTOGRADER_ROOT=/autograder
export SRC_DIR=/autograder/hw/test_suite/src # TODO: decide if this should be in docker file or not

#================= getting the right assignment from github =================================
ASSIGNMENT_NAME=$(cat $AUTOGRADER_ROOT/submission_metadata.json | jq -r '.assignment.title')
declare -A assignment_dict
assignment_dict["C Review and xv6 Introduction"]=lab01-c_review
assignment_dict["Simple Shell"]=lab02-simple_shell
assignment_dict["Process Lab"]=lab03-process_lab
assignment_dict["Heap Manager"]=lab04-heap_manager
assignment_dict["(Challenge) Heap Manager II"]=lab05-heap_manager2
assignment_dict["[Challenge] Copy-on-write"]=lab06-copy_on_write
assignment_dict["Threads & Mutex Basics"]=lab07-threads_mutex_basic
assignment_dict["Condition Variables Basics"]=lab08-cond_vars_basic
assignment_dict["(Challenge) Condition Variables 2"]=lab09-cond_vars2
assignment_dict["Scheduler Activity"]=lab10-xv6_scheduler
assignment_dict["(Challenge) Stack Smashing"]=lab11-stack_smashing
assignment_dict["(Challenge) ext2"]=lab12-ext2

assignment_dict["Exam 1 Part 1"]=exam1
assignment_dict["Exam 1 Part 2"]=exam1_pt2

assignment_dict["Exam 2 Part 1"]=exam2_pt1
assignment_dict["Exam 2 Part 2"]=exam2_pt2

ASSIGNMENT=${assignment_dict[$ASSIGNMENT_NAME]}
#TODO: check if $ASSIGNMENT exisits and can be found

cd /Gradescope_Setup
git pull >/dev/null
cd ..
mkdir -p /autograder/hw/test_suite/src # ensures src is there
cp -r /Gradescope_Setup/hw/$ASSIGNMENT/* /autograder/hw/test_suite/
cp -r /Gradescope_Setup/hw/grading_utils/ /autograder/hw/

#TODO: make submissions dir read only?

#================= run tests_setup.sh that were just pulled from git =================================
# shellcheck disable=SC2164
cd /autograder/hw/test_suite/

echo "--- running tests_setup.sh ---"
bash tests_setup.sh

#================= printing out student name and id =================================
STUDENT_NAME=$(jq '.users[0].name' $AUTOGRADER_ROOT/submission_metadata.json \
                  | tr -d '"' | tr -d ',' | awk '{$1=$1;print}') # removing the "
STUDENT_ID=$(jq '.users[0].email' $AUTOGRADER_ROOT/submission_metadata.json \
                  |tr -d '"' | tr -d ',' | cut -d'@' -f1 | awk '{$1=$1;print}')

echo "Student name: $STUDENT_NAME"
echo "Student ID: $STUDENT_ID"
