#!/usr/bin/env bash

set -e -u -o pipefail # exit on fail
BLUE=$(tput -T xterm-256color setaf 4)
#RESET=$(tput -T xterm-256color sgr0)
export PS4='[$BLUE$BASH_SOURCE\033[0m:$LINENO] '
set -x # turns on logging

# Set up autograder files

#svn up /autograder/hw > /dev/null #svn is no longer supported

#================= set up environment variables =================================
export AUTOGRADER_ROOT=/autograder
export SRC_DIR=/autograder/hw/test_suite/src # TODO: decide if this should be in docker file or not

#================= getting the right assignment from github =================================
# causes a weird double print or [[ in set -x that can't be removed
ASSIGNMENT_NAME=$(jq -r '.assignment.title' $AUTOGRADER_ROOT/submission_metadata.json)

declare -A assignment_dict=(
["Lab 01: C Review and xv6 Introduction"]=lab01-c_review
["Lab 02: Simple Shell"]=lab02-simple_shell
["Lab 03: Process Lab"]=lab03-process_lab
#["Lab 04: Process Lab"]=lab04-debug_lab
["Lab 05: Heap Manager"]=lab05-heap_manager
#["Lab 06: (Challenge) Heap Manager II"]=lab06-heap_manager2
["[Challenge] Lab 06: Copy-on-Write"]=lab07-copy_on_write
["Lab 07: Threads & Mutex Basics"]=lab08-threads_mutex_basic
["Lab 08: Condition Variables Basics"]=lab09-cond_vars_basic
["(Challenge) Lab 09: Condition Variables II"]=lab10-cond_vars2
["Lab 10: Scheduler Activity"]=lab11-xv6_scheduler
["(Challenge) Lab 11: Stack Smashing"]=lab12-stack_smashing
["(Challenge) Lab 12: ext2"]=lab13-ext2

["Exam 1 Part 1"]=exam1
["Exam 1 Part 2"]=exam1_pt2

["Exam 2 Part 1"]=exam2_pt1
["Exam 2 Part 2"]=exam2_pt2
)

# check if assignment name is in dictionary
if ! [[ ${assignment_dict["$ASSIGNMENT_NAME"]+_} ]]; then
  set +x
  RED=$(tput -T xterm-256color setaf 1)
  echo
  echo "$RED"\[ERROR\] Can not find assignment name "$ASSIGNMENT_NAME"
  echo Did you recently change the name of the assignment in gradescope?
  echo If so change the run_autograder script.
  exit 1
fi

ASSIGNMENT=${assignment_dict["$ASSIGNMENT_NAME"]}

cd /Gradescope_Setup
git pull >/dev/null
cd ..
mkdir -p /autograder/hw/test_suite/src # ensures src is there
cp -r /Gradescope_Setup/hw/"$ASSIGNMENT"/* /autograder/hw/test_suite/
cp -r /Gradescope_Setup/hw/grading_utils/ /autograder/hw/

#TODO: make submissions dir read only?

#================= run tests_setup.sh that were just pulled from git =================================
cd /autograder/hw/test_suite/

echo "--- running tests_setup.sh ---"
bash tests_setup.sh

#================= printing out student name and id =================================
set +x # turn off logging
STUDENT_NAME=$(jq '.users[0].name' $AUTOGRADER_ROOT/submission_metadata.json \
                  | tr -d '"' | tr -d ',' | awk '{$1=$1;print}') # removing the "
STUDENT_ID=$(jq '.users[0].email' $AUTOGRADER_ROOT/submission_metadata.json \
                  |tr -d '"' | tr -d ',' | cut -d'@' -f1 | awk '{$1=$1;print}')

echo "Student name: $STUDENT_NAME"
echo "Student ID: $STUDENT_ID"
